#!/usr/bin/env python3
"""
Myography Organizer v3.0 - Compatible with Analyzer v2.9
Splits master Excel by experiment type

UPDATES IN v3.0:
- Compatible with v2.9 analyzer (2 sheets: Overall + 10s bins)
- Recognizes new normalized metrics (Force_Per_Contraction, etc.)
- Removed 30s bins support (no longer generated by analyzer)

This tool organizes analysis results by experiment type:
- Reads master Excel with 2 sheets (Overall_Metrics + 10sec_Bins)
- Classifies files by keywords in filename
- Creates separate folder for each experiment
- Copies both sheets for each experiment's files
- Organizes validation plots
- Handles multiple Excel files (uses most recent)
- Creates timestamped Excel AND validation_plots folders

Author: Geoanna Bautista, Immature Gut Biology Lab
Version: 3.0 - Compatible with Analyzer v2.9 (2 sheets)
Date: January 3, 2026
"""

import pandas as pd
from pathlib import Path
import shutil
import sys
from datetime import datetime

# Classification rules - edit these to add new experiments
EXPERIMENT_RULES = {
    'Ryanodine': ['R_', 'RyR', 'Ryanodine'],
    'Thapsigargin': ['Th_', 'Thapsi', 'Thapsigargin'],
    'WT_vs_KO': ['KO', 'ShWT', 'sham'],
    'Yoda_Only': []  # Catch-all for remaining files
}

def classify_file(filename):
    """
    Classify file by experiment type based on keywords
    
    Returns experiment name or 'Yoda_Only' as default
    """
    # Check each experiment's keywords
    for experiment, keywords in EXPERIMENT_RULES.items():
        if experiment == 'Yoda_Only':
            continue  # Skip catch-all for now
        
        for keyword in keywords:
            if keyword.lower() in filename.lower():
                return experiment
    
    # Default to Yoda_Only if no match
    return 'Yoda_Only'


def organize_results(results_folder, output_base):
    """
    Organize master Excel and validation plots by experiment type
    
    Parameters:
    -----------
    results_folder : str or Path
        Folder containing master Excel and validation_plots (3_Results)
    output_base : str or Path
        Base folder for organized output (project folder)
    """
    results_folder = Path(results_folder)
    output_base = Path(output_base)
    
    print("="*80)
    print("MYOGRAPHY ORGANIZER v3.0 - Compatible with Analyzer v2.9")
    print("="*80)
    print(f"\nResults folder: {results_folder}")
    print(f"Output base: {output_base}\n")
    
    # Find all Excel files
    excel_files = sorted(results_folder.glob("Myography_Analysis_*.xlsx"))
    
    if not excel_files:
        print("❌ ERROR: No Myography_Analysis_*.xlsx file found")
        return
    
    # Handle multiple Excel files
    if len(excel_files) > 1:
        print(f"⚠  Found {len(excel_files)} Excel files in results folder:")
        for ef in excel_files:
            print(f"    - {ef.name}")
        print(f"\n  Using most recent: {excel_files[-1].name}")
        print(f"  (Files are sorted alphabetically, so latest timestamp = last file)\n")
    
    excel_file = excel_files[-1]  # Use most recent (last in sorted list)
    print(f"📊 Using master Excel: {excel_file.name}\n")
    
    # Generate timestamp for output files
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Read BOTH sheets (v2.9 structure)
    print("Reading Excel sheets...")
    try:
        df_overall = pd.read_excel(excel_file, sheet_name='Overall_Metrics')
        df_bins_10s = pd.read_excel(excel_file, sheet_name='10sec_Bins')
        print(f"✓ Loaded 2 sheets successfully (Analyzer v2.9 format)")
        print(f"  - Overall_Metrics: {len(df_overall)} rows, {len(df_overall.columns)} columns")
        print(f"  - 10sec_Bins: {len(df_bins_10s)} rows, {len(df_bins_10s.columns)} columns\n")
        
        # Verify expected column count
        if len(df_overall.columns) == 30:
            print("  ✓ Detected new normalized metrics (v2.9)")
        elif len(df_overall.columns) == 26:
            print("  ⚠ Using v2.8 format (missing normalized metrics)")
        else:
            print(f"  ⚠ Unexpected column count: {len(df_overall.columns)}")
        
    except Exception as e:
        print(f"❌ ERROR reading Excel: {e}")
        print("\nMake sure you're using Analyzer v2.9 output!")
        print("Expected sheets: Overall_Metrics + 10sec_Bins")
        return
    
    # Get unique filenames
    all_filenames = df_overall['Filename'].unique()
    print(f"\nTotal files in Excel: {len(all_filenames)}\n")
    
    # Classify files
    file_classification = {}
    for filename in all_filenames:
        experiment = classify_file(filename)
        if experiment not in file_classification:
            file_classification[experiment] = []
        file_classification[experiment].append(filename)
    
    # Print classification summary
    print("Classification Summary:")
    print("-" * 80)
    for experiment, files in sorted(file_classification.items()):
        print(f"  {experiment}: {len(files)} files")
    print("-" * 80 + "\n")
    
    # Create organized folders and Excel files
    created_files = []
    for experiment, filenames in file_classification.items():
        print(f"Processing {experiment}...")
        
        # Create experiment folder inside 3_Results (same folder each time)
        exp_folder = results_folder / experiment
        exp_folder.mkdir(parents=True, exist_ok=True)
        
        # Filter each sheet for this experiment's files
        exp_overall = df_overall[df_overall['Filename'].isin(filenames)].copy()
        exp_bins_10s = df_bins_10s[df_bins_10s['Filename'].isin(filenames)].copy()
        
        # Check if ANY Excel already exists in folder - if so, use timestamp
        existing_excels = list(exp_folder.glob(f"{experiment}*.xlsx"))
        if existing_excels:
            # Use timestamped filename in SAME folder
            exp_excel_path = exp_folder / f"{experiment}_{timestamp}.xlsx"
            plots_subfolder = exp_folder / f'validation_plots_{timestamp}'
            print(f"  ⚠  Found {len(existing_excels)} existing Excel file(s), creating timestamped version")
        else:
            exp_excel_path = exp_folder / f"{experiment}.xlsx"
            plots_subfolder = exp_folder / 'validation_plots'
        
        plots_subfolder.mkdir(exist_ok=True)
        
        # Write 2 sheets (v2.9 format)
        with pd.ExcelWriter(exp_excel_path, engine='openpyxl') as writer:
            exp_overall.to_excel(writer, sheet_name='Overall_Metrics', index=False)
            exp_bins_10s.to_excel(writer, sheet_name='10sec_Bins', index=False)
        
        created_files.append(exp_excel_path.name)
        print(f"  ✓ Created {exp_excel_path.name} ({len(filenames)} files)")
        
        # Copy validation plots to timestamped folder
        plots_source = results_folder / 'validation_plots'
        if plots_source.exists():
            copied_plots = 0
            for filename in filenames:
                # Plot filename is [filename]_validation.png
                plot_file = f"{filename}_validation.png"
                source_plot = plots_source / plot_file
                
                if source_plot.exists():
                    dest_plot = plots_subfolder / plot_file
                    shutil.copy2(str(source_plot), str(dest_plot))
                    copied_plots += 1
            
            print(f"  ✓ Copied {copied_plots} validation plots to {plots_subfolder.name}/\n")
        else:
            print(f"  ⚠  No validation_plots folder found\n")
    
    # Summary
    print("="*80)
    print("ORGANIZATION COMPLETE!")
    print("="*80)
    print(f"\nOrganized into {len(file_classification)} experiment folders:")
    print(f"\nAll folders are in: {results_folder}/\n")
    
    for experiment, files in sorted(file_classification.items()):
        exp_folder = results_folder / experiment
        excel_files_in_folder = sorted(exp_folder.glob(f"{experiment}*.xlsx"))
        plots_folders = sorted(exp_folder.glob("validation_plots*"))
        
        print(f"  {experiment}/")
        for ef in excel_files_in_folder:
            print(f"    ├── {ef.name}")
        for pf in plots_folders:
            plot_count = len(list(pf.glob("*.png")))
            print(f"    ├── {pf.name}/ ({plot_count} plots)")
    
    print("\n" + "="*80)
    print("\n💡 NOTES:")
    print("  - All .txt files are in: 2_Processed/")
    print("  - Experiment folders are in: 3_Results/")
    print("  - Each run creates timestamped Excel + validation_plots folder")
    print("  - Original validation_plots in 3_Results/ preserved")
    print("  - Compatible with Analyzer v2.9 (2 sheets)")
    print("="*80 + "\n")


def main():
    """Main entry point"""
    
    if len(sys.argv) != 3:
        print("\n❌ ERROR: Incorrect number of arguments")
        print("\nUsage:")
        print("  python3 myography_organizer.py [results_folder] [output_base]")
        print("\nExample:")
        print("  python3 myography_organizer.py ../Projects/Piezo1_Adult/3_Results ../Projects/Piezo1_Adult")
        print("\n")
        sys.exit(1)
    
    results_folder = sys.argv[1]
    output_base = sys.argv[2]
    
    organize_results(results_folder, output_base)


if __name__ == "__main__":
    main()
